### PR TITLE
Add travis-ci integration

### PR DESCRIPTION
**Pull request by gabro**

### CODE REVIEW

**Comment by gabro** [comment]
Still work in progress, Semantic UI hangs the build as it requires user interaction. See https://github.com/Semantic-Org/Semantic-UI/issues/1816

**Comment by gabro** [comment]
Build fails with

> rm -rf node_modules/react-router/node_modules/react && pushd node_modules/react-router && npm run-script build-npm && popd

this is because `pushd`/ `pop` are bash extensions.

**Comment by gabro** [comment]
@giogonzo PLZ review and merge

**Comment by giogonzo** [comment]
@gabro :eyes:  515e04e

**Comment by gabro** [comment]
Woops, good catch, don't know how it got in there.
I've rebased it away, it should be fine now, @giogonzo

**Pull request merged**
